In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 120.0 KB

In [4]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [5]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [6]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [7]:
df.shape

(542, 18)

In [8]:
df.duplicated(['Customer_ID']).sum()

np.int64(8)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [11]:
df[df.duplicated(['Customer_ID'])]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
524,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,04-06-2025

In [12]:
df.drop(524,inplace=True)

In [13]:
df.duplicated(['Customer_ID']).sum()

np.int64(0)

In [14]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [15]:
df.shape

(534, 18)

In [16]:
df.replace(['N/A','NULL','',' '],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [17]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 534 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            534 non-null    str
 1   Customer_Name          526 non-null    str
 2   Gender                 529 non-null    str
 3   Age                    528 non-null    float64
 4   State                  524 non-null    str
 5   City                   529 non-null    str
 6   Tenure_Months          527 non-null    float64
 7   Subscription_Type      523 non-null    str
 8   Monthly_Charges        522 non-null    float64
 9   Total_Charges          526 non-null    float64
 10  Contract_Type          531 non-null    str
 11  Payment_Method         519 non-null    str
 12  Internet_Service       528 non-null    str
 13  Tech_Support           523 non-null    str
 14  Senior_Citizen         527 non-null    str
 15  Dependents             532 non-null    str
 16  Churn                  531 non-null    str
 17  Last_Interaction_Date  532 non-null    str
dtypes: float64(4), str(14)
memory usage: 122.3 KB

In [19]:
df = df.apply(lambda x: x.str.strip() if x.dtype=='str' else x)

In [20]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [21]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     183
Standard    169
Basic       167
basic         2
BASIC         2
Name: count, dtype: int64

In [22]:
df.head(3)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026

In [23]:
df['Payment_Method'].value_counts()

Payment_Method
Debit Card     110
UPI            109
Cash           103
Credit Card     99
Net Banking     98
Name: count, dtype: int64

In [24]:
df['Dependents'].value_counts()

Dependents
No     269
Yes    263
Name: count, dtype: int64

In [25]:
df['Internet_Service'].value_counts()

Internet_Service
Fiber    140
Cable    133
DSL      129
5G       126
Name: count, dtype: int64

In [26]:
df['Senior_Citizen'].value_counts()

Senior_Citizen
No     424
Yes    103
Name: count, dtype: int64

In [27]:
df['Senior_Citizen'].value_counts()

Senior_Citizen
No     424
Yes    103
Name: count, dtype: int64

In [28]:
df['Customer_Name'] = df['Customer_Name'].str.title()
df['State'] = df['State'].str.title()
df['City'] = df['City'].str.title()
df['Subscription_Type'] = df['Subscription_Type'].str.title()
df['Contract_Type'] = df['Contract_Type'].str.title()

In [29]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     183
Basic       171
Standard    169
Name: count, dtype: int64

In [30]:
df['Churn'].value_counts()

Churn
No     404
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [31]:
df['Churn'] = df['Churn'].str.title()

In [32]:
df['Churn'].value_counts()

Churn
No     404
Yes    127
Name: count, dtype: int64

In [33]:
df.info()

<class 'pandas.DataFrame'>
Index: 534 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            534 non-null    str
 1   Customer_Name          526 non-null    str
 2   Gender                 529 non-null    str
 3   Age                    528 non-null    float64
 4   State                  524 non-null    str
 5   City                   529 non-null    str
 6   Tenure_Months          527 non-null    float64
 7   Subscription_Type      523 non-null    str
 8   Monthly_Charges        522 non-null    float64
 9   Total_Charges          526 non-null    float64
 10  Contract_Type          531 non-null    str
 11  Payment_Method         519 non-null    str
 12  Internet_Service       528 non-null    str
 13  Tech_Support           523 non-null    str
 14  Senior_Citizen         527 non-null    str
 15  Dependents             532 non-null    str
 16  Churn                  531 non-null    str
 17  Last_Interaction_Date  532 non-null    str
dtypes: float64(4), str(14)
memory usage: 122.3 KB

In [34]:
# df = df.apply(lambda x: x.str.strip() if x.dtype=='str' else x)

df = df.apply(lambda x: x.str.title() if x.dtype=='str' else x)
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,Dsl,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,Upi,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,Up,Kanpur,30.0,Basic,1341.52,NaN,Month-To-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [35]:
df['Gender'].value_counts()

Gender
Female    269
Male      260
Name: count, dtype: int64

In [36]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [37]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  528.000000     527.000000       522.000000     526.000000
mean    44.335227      36.497154      1328.054732   49622.650285
std     18.652503      20.672889       712.791278   41586.449512
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.995000   18794.280000
50%     44.000000      38.000000      1295.855000   40299.800000
75%     57.000000      54.000000      1877.910000   74535.230000
max    165.000000      72.000000      2492.510000  171429.830000

In [38]:
df = df[(df['Age'] >= 18) & (df['Age'] <=100)]

In [39]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  518.000000     511.000000       507.000000     510.000000
mean    43.405405      36.389432      1329.300454   50072.877608
std     15.495233      20.553589       717.018414   41214.574538
min     18.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18928.310000
50%     43.000000      38.000000      1294.600000   40737.755000
75%     56.750000      54.000000      1879.020000   74535.230000
max     70.000000      72.000000      2492.510000  171429.830000

In [40]:
df = df[df['Monthly_Charges'] >=0]

df = df[df['Total_Charges'] >=0]

In [41]:
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,12-10-2025
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,26-12-2025
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
536,C5004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025

In [42]:
df['Last_Interaction_Date'] = pd.to_datetime(df['Last_Interaction_Date'],errors='coerce')

In [43]:
df.isnull().sum()

Customer_ID                0
Customer_Name              5
Gender                     4
Age                        0
State                      7
City                       5
Tenure_Months              5
Subscription_Type          6
Monthly_Charges            0
Total_Charges              0
Contract_Type              2
Payment_Method            15
Internet_Service           6
Tech_Support               9
Senior_Citizen             6
Dependents                 1
Churn                      2
Last_Interaction_Date    314
dtype: int64

In [44]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,Upi,Dsl,Yes,No,No,No,NaT
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,NaT

In [45]:
df['Tech_Support'] = df['Tech_Support'].fillna('No')

df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

df['Monthly_Charges'] = df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean())

df['Total_Charges'] = df['Total_Charges'].fillna(df['Total_Charges'].mean())

df['Age'] = df['Age'].fillna(df['Age'].mean())

In [46]:
df.isnull().sum()

Customer_ID                0
Customer_Name              5
Gender                     4
Age                        0
State                      7
City                       5
Tenure_Months              5
Subscription_Type          6
Monthly_Charges            0
Total_Charges              0
Contract_Type              2
Payment_Method             0
Internet_Service           6
Tech_Support               0
Senior_Citizen             6
Dependents                 1
Churn                      2
Last_Interaction_Date    314
dtype: int64

In [47]:
df.head(2)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,2025-12-10
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT

In [48]:
# Customer lifytime value

df['Customer_Value'] = df['Monthly_Charges']*df['Tenure_Months']

In [49]:
df['Monthly_Revenue'] = df['Monthly_Charges']

In [50]:
df['Senior_Flag'] = np.where(df['Age'] >=60,'Senior','Adult')

In [51]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Senior_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Upi,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,Debit Card,5G,No,No,No,Yes,NaT,7215.39,555.03,Adult
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,Adult
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Upi,Dsl,Yes,No,No,No,NaT,140618.10,2008.83,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cash,Cable,Yes,Yes,Yes,No,NaT,125182.26,2196.18,Senior

In [52]:
# Churn flag

df['Churn_Flag'] = df['Churn'].map({'Yes':1,'No':0})

In [53]:
bins = [0,12,24,48,72]

label = labels = ['0-12 month','13-24 month','25-48 month','49-72 month']

df['Tenure_Group'] = pd.cut(df['Tenure_Months'],bins=bins,labels=label)

In [54]:
df['Last_Interaction_Date'] = df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

In [55]:
df.shape

(491, 23)

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 491 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            491 non-null    str
 1   Customer_Name          486 non-null    str
 2   Gender                 487 non-null    str
 3   Age                    491 non-null    float64
 4   State                  484 non-null    str
 5   City                   486 non-null    str
 6   Tenure_Months          486 non-null    float64
 7   Subscription_Type      485 non-null    str
 8   Monthly_Charges        491 non-null    float64
 9   Total_Charges          491 non-null    float64
 10  Contract_Type          489 non-null    str
 11  Payment_Method         491 non-null    str
 12  Internet_Service       485 non-null    str
 13  Tech_Support           491 non-null    str
 14  Senior_Citizen         485 non-null    str
 15  Dependents             490 non-null    str
 16  Churn                  489 non-null    str
 17  Last_Interaction_Date  491 non-null    datetime64[us]
 18  Customer_Value         486 non-null    float64
 19  Monthly_Revenue        491 non-null    float64
 20  Senior_Flag            491 non-null    str
 21  Churn_Flag             489 non-null    float64
 22  Tenure_Group           486 non-null    category
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 126.1 KB

In [57]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Churn_Flag
count,491.000000,486.000000,491.000000,491.000000,491,486.000000,491.000000,489.000000
mean,43.195519,36.034979,1357.248310,50239.882933,2025-09-14 04:09:17.230142,50175.936708,1357.248310,0.237219
min,18.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,30.000000,19.000000,762.910000,19088.300000,2025-09-06 00:00:00,19108.912500,762.910000,0.000000
50%,43.000000,38.000000,1306.800000,40649.600000,2025-09-06 00:00:00,40701.195000,1306.800000,0.000000
75%,56.000000,53.000000,1882.895000,73712.710000,2025-09-06 00:00:00,73757.105000,1882.895000,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,15.417008,20.479027,652.328938,39705.180915,NaN,39710.645735,652.328938,0.425813

In [58]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            5
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           5
Monthly_Revenue          0
Senior_Flag              0
Churn_Flag               2
Tenure_Group             5
dtype: int64

In [59]:
df['Churn_Flag'].value_counts()

Churn_Flag
0.0    373
1.0    116
Name: count, dtype: int64

In [60]:
# Export


df.to_csv('Clean_Churn_Data.csv',index=False)

In [61]:
# Export into MySql

from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/churn_db"
)

In [62]:
engine = create_engine(
    "mysql+pymysql://root:Sanjeet%409973@localhost:3306/churn_db"
)

In [63]:
with engine.connect() as connection:
    print("MySQL Connected Successfully!")

MySQL Connected Successfully!

In [64]:
df.to_sql(
    "customer_churn",
    con=engine,
    if_exists="replace",
    index=False
)

491